[font]
normal = { family="Hurmit Nerd Font", style="regular" }

[window]
padding = { x = 8, y = 8 }
opacity = 0.9

[colors]
cursor     = { text = "#181818", cursor = "#ff8844" }

[colors.primary]
background = "#2e3436"
foreground = "#d3d7cf"

[colors.normal]
black   =  "#3b4252"
red     =  "#d32f2f"
green   =  "#388e3c"
yellow  =  "#ffa726"
blue    =  "#1976d2"
magenta =  "#663399"
cyan    =  "#00838f"
white   =  "#d3d7cf"

[colors.bright]
black   =  "#4f5b66"
red     =  "#e57373"
green   =  "#81c784"
yellow  =  "#ffd54f"
blue    =  "#64b5f6"
magenta =  "#b39ddb"
cyan    =  "#4dd0e1"
white   =  "#f0f0f0"
